knp_gaufrette:
    adapters:
        test_media:
            local:
                directory: %kernel.root_dir%/../web/uploads/media
                create: true
    filesystems:
        test_media:
            adapter: test_media

tms_media:
    storage_mappers:
        testmedia:
            storage_provider: gaufrette.test_media_filesystem
            rules:
                mime_types: ['image/jpg', 'image/png', 'image/jpeg']
