fos_elastica:
    clients:
        default:
          host: %elasticsearch_host%
          port: %elasticsearch_port%
    indexes:
        tms_media:
            types:
                media:
                    properties:
                        id: { type: integer }
                        source: { type: string, index: not_analyzed }
                        referencePrefix: { type: string, index: not_analyzed }
                        extension: { type: string, index: not_analyzed }
                        size: { type: integer }
                        createdAt: { type: date, format: date_time_no_millis }
                    persistence:
                        driver: orm
                        model: Tms\Bundle\MediaBundle\Entity\Media
                        provider: ~
                        listener: ~
                        finder: ~
